stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

before_script:
  - echo "Using Java 17 and Maven"

build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar