stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Using Java 17 and Maven"
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
  - export PATH=$JAVA_HOME/bin:$PATH

build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar