version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-store
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storedb
      MYSQL_USER: storeuser
      MYSQL_PASSWORD: storepass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  store-api:
    build: .
    container_name: store-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql